services:
  wytryszki:
    image: ghcr.io/jandziaslo/apache2-php-docker
    container_name: wytryszki
    restart: unless-stopped
    ports:
      - "80:8081"
    volumes:
      - ./data:/var/www/wytryszki/data
      - ./wytryszki.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
